#ifndef _SD_CARD_IO_RTEMS_CONFIG_H_
#define _SD_CARD_IO_RTEMS_CONFIG_H_

#define CONFIGURE_USE_IMFS_AS_BASE_FILESYSTEM
#define CONFIGURE_FILESYSTEM_DOSFS
#define CONFIGURE_MAXIMUM_DRIVERS					10
#define CONFIGURE_MAXIMUM_SEMAPHORES				(4*RTEMS_DOSFS_SEMAPHORES_PER_INSTANCE)
#define CONFIGURE_LIBIO_MAXIMUM_FILE_DESCRIPTORS	30
#define CONFIGURE_APPLICATION_NEEDS_LIBBLOCK
#define CONFIGURE_POSIX_INIT_TASKS_TABLE
#define CONFIGURE_BDBUF_MAX_READ_AHEAD_BLOCKS		(16)
#define CONFIGURE_BDBUF_MAX_WRITE_BLOCKS			(64)
#define CONFIGURE_BDBUF_BUFFER_MIN_SIZE				(512)
#define CONFIGURE_BDBUF_BUFFER_MAX_SIZE				(32 * 1024)
#define CONFIGURE_BDBUF_CACHE_MEMORY_SIZE			(4 * 1024 * 1024)

#endif /* _SD_CARD_IO_RTEMS_CONFIG_H_ */
