/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EoT_Python_MQTT;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

class MyCanvas extends JPanel {

    ImageIcon ii;

    public MyCanvas(ImageIcon ii) {
        this.ii = ii;
    }
    
    void changeImage(ImageIcon ii) {
        this.ii = ii;
    }

    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        double scalex = ((double) this.getHeight()) / ii.getIconHeight();
        double scaley = ((double) this.getWidth()) / ii.getIconWidth();
        if (scalex < scaley) {
            g2d.drawImage(ii.getImage(), 0, 0, (int) (ii.getIconWidth() * scalex), this.getHeight(), Color.BLACK, this);
        } else {
            g2d.drawImage(ii.getImage(), 0, 0, this.getWidth(), (int) (ii.getIconHeight() * scaley), Color.BLACK, this);
        }
        this.repaint();
    }
}

/**
 *
 * @author DELL2
 */
public class ImageFrame extends javax.swing.JFrame {

    private static final String IMAGE_URL = "/resource/bar.png";
    private MyCanvas ipan;
    /**
     * Creates new form frame
     */
    public ImageFrame(ImageIcon image) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ipan = new MyCanvas(image);
        this.add(this.ipan);
        this.repaint();
    }

    void changeImage(ImageIcon image) {
        this.ipan.changeImage(image);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
